version: '3'
services:
  webstack_hugo:
    container_name: webstack_hugo
    image: webstack_hugo:v1
    working_dir: /site
    restart: always
    ports:
      - 1313:1313
    #volumes:
    command:
      - /usr/bin/hugo
      - server
      - --bind
      - 0.0.0.0